### ISSUE TITLE
What is the "leftover"

### ISSUE THREAD

**Issue by petero-dk** [baol/waving-z#2]
When running the wave-in the following output comes:

```
[ ] 
3e 6b 33 84 84 
[ ] 
6d e9 2a a9 1e 84 
[ ] 

[ ] 
64 a5 78 7d 68 6b 4c cb 64 a9 06 aa 8e 
[ ] 
e8 67 e9 8b 55 48 b4 84 58 85 
[ ] 
e6 00 93 34 95 8f 
[ ] 
12 4a 0a 
[ ] 
cb 96 a6 a4 b5 55 95 55 
[ ] 
1a b6 2b 1a 44 1a 
[ ] 
ab 1a 56 a6 98 23 0b 21 
[ ] 
2b 
[ ] 
45 28 
[ ] 
21 65 59 2a 
[ ] 
8a 62 5c 07 46 62 96 51 26 ec a7 ad 22 11 22 a0 12 4a 
[ ] 
ad 7c b2 e8 b3 9d cb d7 ac 
[ ] 
4b 62 82 
[ ] 
92 25 28 
[ ] 
ea b2 8b 48 55 92 
[ ] 
ca a4 d9 c9 66 93 2d 52 58 
[ ] 

[ ] 
23 d4 91 40 55 48 
[ ] 
d5 29 61 aa 
[ ] 
52 a8 a1 
[ ] 
c3 d0 09 8b 20 81 04 0d 01 03 10 2e fa 00 40 2a 28 89 
[x] HomeId: c3d0098b, SourceNodeId: 20, FC0: 81, FC1: 4, FC[speed=0 low_power=0 ack_request=0 header_type=1 beaming_info=0 seq=4], Length: 13, DestNodeId: 1, CommandClass: 3, Payload: 10 2e 
c3 d0 09 8b 20 03 06 0a 2e 6f 00 02 28 a3 25 49 2c 52 20 24 12 80 50 51 
[x] HomeId: c3d0098b, SourceNodeId: 20, FC0: 3, FC1: 6, FC[speed=0 low_power=0 ack_request=0 header_type=3 beaming_info=0 seq=6], Length: 10, DestNodeId: 46, CommandClass: 6f, Payload: 
```

It seems there is a lot of "other" data that is not parsed as Z-Wave, additionally the parsed Z-Wave does not seem to fit, the commandclasses are not what is expected and there are many unidentified homeids. One I can identify, and many not identified, when I run it for an extended period of time.

**Comment by baol** [comment]
The noisy signal that is read from the radio is interpreted as bits, this bits sometimes look like a start of frame. There are several levels of interpretation. From "I ear noise, but no signal" to "this looks like a signal" to "this signal actually contains some data" to "this data looks like a complete frame and the checksum is/is not ok" to "I know this homeid, this message is for me". The code should be self-explanatory, hopefully.
