### ISSUE TITLE
SIGSEGV in zwave_print

### ISSUE THREAD

**Issue by flebourse** [baol/waving-z#3]
In a noisy environment severely corrupt frames can appear:
 - no data
 - null length reported
The test : if (len < sizeof(packet_t) || len < p.length)
isn't careful enough, it should be replaced by:
if (data_begin == 0 || p.length == 0 || len < sizeof(packet_t) || len < p.length)
With this patch wave-in runs several hours without issues.

**Comment by baol** [comment]
Good catch! Would you mind creating a very small and focused pull request with this corrected line?

**Comment by baol** [comment]
thanks!
